### ISSUE TITLE
name change on call-consensus-reads?

### ISSUE THREAD

**Issue by colindaven** [rust-bio/rust-bio-tools#48]
Hi, 
this call-consensus-reads sounds very different to what it actually does. Why not call it remove-dups or similar ? Calling consensus sounds more like read merging and quality correction like with SPOA / racon etc.

Just my two cents, thanks for the interesting library.
Colin

    call-consensus-reads     Tool to remove PCR duplicates from either FASTQ or BAM files.

                             Requirements:
                               - starcode

**Comment by HenningTimm** [comment]
Hi Colin and thank you for the feedback. I can see where this might be confused.

The intent was to differentiate that we use all PCR duplicates of a read to compute a consensus sequnece (incorporating quality values etc.) instead of just removing duplicates. So maybe something along the lines of:
* merge-pcr-duplicates/ merge-pcr-dups
* pcr-consensus-reads (Would that be sufficiently distinct from the long read applications in your book?)
* pcr-duplicate-consensus/ pcr-dup-consensus 

might communicate this better?

**Comment by dlaehnemann** [comment]
And maybe change the wording of the tool description, because currently it does explicitly state that the tool `remove`s duplicates, which it doesn't, right? It instead merges duplicates, only removing redundancy, but improving quality in the process...

**Comment by colindaven** [comment]
Exactly, I would change it to 

`merge-pcr-duplicates`

and add description

```
Merge PCR duplicates, reducing redundancy but increasing quality, from either FASTQ or BAM files.

                         Requirements:
                           - starcode
```

**Comment by johanneskoester** [comment]
It also merges horizontally overlapping read pairs, doesn't it? Ideally the name would mention that as well.

**Comment by johanneskoester** [comment]
In a sense what it does is that it tries to predict the maximul likelihood fragment sequence from overlapping and duplicate reads. Some options: `predict-fragment-sequence`, `reads-to-fragments`, `collapse-reads-to-fragments`, `reads2fragments`.

**Comment by colindaven** [comment]
Ok, maybe

`collapse-reads-to-fragments`

With a good description summarizing the (extensive) functionality mentioned here. Sounds like an interesting tool!

**Comment by johanneskoester** [comment]
Sounds good for me. @FelixMoelder please change the name whenever you find the time.
